"$schema" = 'https://starship.rs/config-schema.json'

[character] # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"

[cmd_duration]
min_time = 500
format = "underwent [$duration](bold yellow)"

[directory]
read_only = " "
truncation_length = 1
